### ISSUE TITLE
when createZodDto is imported, server side library can't be tree-shaked.

### ISSUE THREAD

**Issue by Insik-Won** [risenforces/nestjs-zod#1]
I'm using yarn berry and using nestjs-zod for validating dtos.
I want to import createZodDto in client-side without installing no server-side library.
but i can't because createZodDto is imported from index.ts which imports other server-side dependent files. 

I suggest it should be in other folder, where server-side library is not related with.

**Comment by risenforces** [comment]
@Insik-Won will it be ok for you if I just add `/dto` scope to library? I mean without removing `createZodDto` from main `index` file. It's good for backward compatibility and public API. There may be some issues with imports intellisense, for example it can suggest importing from `nestjs-zod` instead of `nestjs-zod/dto`. But you can set up ESLint to warn about `nestjs-zod` imports on client, and I think this will be enough useful. What do you think?

**Comment by risenforces** [comment]
Closing as no feedback was provided. Feel free to re-open if the problem still exists.

**Comment by frisch-raphael** [comment]
Was facing the the same problem and the /dto did it for me. Thanks a lot @risenforces
